"""add venta_decision y venta_decision_item

Revision ID: 7d234a317752
Revises: b6021663f5c4
Create Date: 2025-09-26 13:15:10.515345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d234a317752'
down_revision = 'b6021663f5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tt_ventas_dias', sa.Integer(), nullable=True),
    sa.Column('vigencia_cotizacion', sa.String(length=120), nullable=True),
    sa.Column('profit_total', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('venta_total', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('margen_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('solicitante_nombre', sa.String(length=120), nullable=True),
    sa.Column('solicitante_email', sa.String(length=120), nullable=True),
    sa.Column('solicitante_tel', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opcion_id'], ['cotizacion_opcion.id'], name=op.f('fk_venta_decision_opcion_id_cotizacion_opcion')),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], name=op.f('fk_venta_decision_solicitud_id_solicitud')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_decision'))
    )
    op.create_table('venta_decision_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('concepto_nombre', sa.String(length=300), nullable=True),
    sa.Column('proveedor', sa.String(length=160), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('unidad', sa.String(length=40), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tarifa', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('costo_unit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('iva', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ret', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('profit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('venta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('margen_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tyc_internos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['venta_decision.id'], name=op.f('fk_venta_decision_item_decision_id_venta_decision')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_decision_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_decision_item')
    op.drop_table('venta_decision')
    # ### end Alembic commands ###
