"""baseline schema

Revision ID: b6021663f5c4
Revises: 
Create Date: 2025-09-12 12:06:38.568888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6021663f5c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('unidad', sa.String(length=32), nullable=True),
    sa.Column('iva_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ret_iva_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('isr_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepto'))
    )
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepto_clave'), ['clave'], unique=True)

    op.create_table('folio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folio'))
    )
    with op.batch_alter_table('folio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folio_codigo'), ['codigo'], unique=True)

    op.create_table('cotizacion_opcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=200), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('cbm_cotizado', sa.Float(), nullable=True),
    sa.Column('origen_final', sa.String(length=200), nullable=True),
    sa.Column('destino_final', sa.String(length=200), nullable=True),
    sa.Column('frecuencia', sa.String(length=100), nullable=True),
    sa.Column('transito_estimado_dias', sa.Integer(), nullable=True),
    sa.Column('dias_libres_destino', sa.Integer(), nullable=True),
    sa.Column('terminos_condiciones', sa.Text(), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], name=op.f('fk_cotizacion_opcion_solicitud_id_solicitud')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cotizacion_opcion'))
    )
    with op.batch_alter_table('cotizacion_opcion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotizacion_opcion_solicitud_id'), ['solicitud_id'], unique=False)

    op.create_table('cotizacion_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=True),
    sa.Column('concepto_nombre', sa.String(length=255), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('unidad', sa.String(length=32), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('precio_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('iva_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ret_iva_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('isr_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto.id'], name=op.f('fk_cotizacion_item_concepto_id_concepto')),
    sa.ForeignKeyConstraint(['opcion_id'], ['cotizacion_opcion.id'], name=op.f('fk_cotizacion_item_opcion_id_cotizacion_opcion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cotizacion_item'))
    )
    with op.batch_alter_table('cotizacion_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotizacion_item_opcion_id'), ['opcion_id'], unique=False)

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('child_seq', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_solicitud_folio_id'), ['folio_id'], unique=False)
        batch_op.create_unique_constraint('uq_folio_childseq', ['folio_id', 'child_seq'])
        batch_op.create_foreign_key(batch_op.f('fk_solicitud_folio_id_folio'), 'folio', ['folio_id'], ['id'])

    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitud_servicio_solicitud_id'))
        batch_op.create_index(batch_op.f('ix_solicitud_servicio_solicitud_id'), ['solicitud_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitud_servicio_solicitud_id'))
        batch_op.create_index(batch_op.f('ix_solicitud_servicio_solicitud_id'), ['solicitud_id'], unique=False)

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_solicitud_folio_id_folio'), type_='foreignkey')
        batch_op.drop_constraint('uq_folio_childseq', type_='unique')
        batch_op.drop_index(batch_op.f('ix_solicitud_folio_id'))
        batch_op.drop_column('child_seq')
        batch_op.drop_column('folio_id')

    with op.batch_alter_table('cotizacion_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotizacion_item_opcion_id'))

    op.drop_table('cotizacion_item')
    with op.batch_alter_table('cotizacion_opcion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotizacion_opcion_solicitud_id'))

    op.drop_table('cotizacion_opcion')
    with op.batch_alter_table('folio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folio_codigo'))

    op.drop_table('folio')
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepto_clave'))

    op.drop_table('concepto')
    # ### end Alembic commands ###
