"""venta_decision add pdf_path and tyc_internos

Revision ID: d5cca4719df6
Revises: 7d234a317752
Create Date: 2025-09-26 14:04:08.056371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cca4719df6'
down_revision = '7d234a317752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_decision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tyc_internos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_decision', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')
        batch_op.drop_column('tyc_internos')

    # ### end Alembic commands ###
