"""baseline schema

Revision ID: 5edf09ec4627
Revises: 
Create Date: 2025-09-09 23:35:43.291782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edf09ec4627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('numero_serie', sa.String(length=32), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=2), nullable=False),
    sa.Column('vendedor', sa.String(length=120), nullable=False),
    sa.Column('sales_support', sa.String(length=120), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('cliente_tipo', sa.Enum('CLIENTE', 'PROSPECTO', name='cliente_tipo_enum'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('prospecto_nombre', sa.String(length=200), nullable=True),
    sa.Column('tipo_embarque', sa.String(length=10), nullable=False),
    sa.Column('incoterm', sa.String(length=10), nullable=False),
    sa.Column('un_clase', sa.String(length=50), nullable=True),
    sa.Column('estibable', sa.Boolean(), nullable=False),
    sa.Column('tipo_cambio', sa.String(length=10), nullable=True),
    sa.Column('valor_factura', sa.Float(), nullable=True),
    sa.Column('seguro', sa.Boolean(), nullable=False),
    sa.Column('origen_pais', sa.String(length=80), nullable=False),
    sa.Column('origen_ciudad', sa.String(length=80), nullable=False),
    sa.Column('origen_cp', sa.String(length=10), nullable=False),
    sa.Column('origen_recoleccion', sa.String(length=200), nullable=True),
    sa.Column('origen_puerto', sa.String(length=120), nullable=True),
    sa.Column('origen_cruce', sa.String(length=120), nullable=True),
    sa.Column('origen_despacho', sa.String(length=10), nullable=True),
    sa.Column('destino_pais', sa.String(length=80), nullable=False),
    sa.Column('destino_ciudad', sa.String(length=80), nullable=False),
    sa.Column('destino_cp', sa.String(length=10), nullable=False),
    sa.Column('destino_entrega', sa.String(length=200), nullable=True),
    sa.Column('destino_puerto', sa.String(length=120), nullable=True),
    sa.Column('destino_cruce', sa.String(length=120), nullable=True),
    sa.Column('destino_despacho', sa.String(length=10), nullable=True),
    sa.Column('unidad', sa.String(length=80), nullable=False),
    sa.Column('servicio_unidad', sa.String(length=80), nullable=False),
    sa.Column('maniobra', sa.String(length=80), nullable=False),
    sa.Column('numero_contenedor', sa.String(length=50), nullable=False),
    sa.Column('tipo_contenedor', sa.String(length=50), nullable=True),
    sa.Column('commodity', sa.String(length=200), nullable=False),
    sa.Column('tipo_carga', sa.String(length=50), nullable=False),
    sa.Column('peso_unidad', sa.String(length=10), nullable=False),
    sa.Column('longitud_unidad', sa.String(length=10), nullable=False),
    sa.Column('volumen_cbm', sa.Float(), nullable=False),
    sa.Column('cotiza_por', sa.String(length=20), nullable=False),
    sa.Column('no_s', sa.Integer(), nullable=True),
    sa.Column('dimensiones_totales', sa.String(length=200), nullable=True),
    sa.Column('cbm_totales', sa.Float(), nullable=True),
    sa.Column('gw_totales', sa.Float(), nullable=True),
    sa.Column('vw_totales', sa.Float(), nullable=True),
    sa.Column('no_dim', sa.Integer(), nullable=True),
    sa.Column('largo_dim', sa.Float(), nullable=True),
    sa.Column('ancho_dim', sa.Float(), nullable=True),
    sa.Column('alto_dim', sa.Float(), nullable=True),
    sa.Column('peso_dim', sa.Float(), nullable=True),
    sa.Column('totales_json', sa.Text(), nullable=True),
    sa.Column('dimensiones_json', sa.Text(), nullable=True),
    sa.Column('servicios_solicitados', sa.Text(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('asunto_email', sa.String(length=200), nullable=True),
    sa.Column('estatus', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitud_estatus'), ['estatus'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitud_numero_serie'), ['numero_serie'], unique=True)

    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('tarifas_json', sa.Text(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('creada_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotizacion_solicitud_id'), ['solicitud_id'], unique=False)

    op.create_table('solicitud_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.Enum('AEREO', 'MARITIMO', 'TERRESTRE', name='tipo_servicio_enum'), nullable=False),
    sa.Column('modalidad', sa.Enum('FCL', 'LCL', name='modalidad_enum'), nullable=True),
    sa.Column('detalle_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitud_servicio_solicitud_id'), ['solicitud_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_servicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitud_servicio_solicitud_id'))

    op.drop_table('solicitud_servicio')
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotizacion_solicitud_id'))

    op.drop_table('cotizacion')
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitud_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_solicitud_estatus'))

    op.drop_table('solicitud')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
